# This file builds all of the tests for our framework

CC=g++
CFLAGS= -std=c++11 -Wall
all: blackboard

blackboard:
	$(CC) $(CFLAGS) blackboard.cpp ../Blackboard.cpp -o blackboard_test

clean:
	rm blackboard_test *~
